### ISSUE TITLE
create suave.sdsc.edu

### ISSUE THREAD

**Issue by izaslavsky** [liside/SuAVE#22]
.. and link it to the Ubuntu version, http://132.249.238.135/

**Comment by izaslavsky** [comment]
then add a redirect from besuave to this

**Comment by valentinedwv** [comment]
http://suave.sdsc.edu/

**Comment by izaslavsky** [comment]
Great! I guess menu navigation in WP has to be adjusted to this domain now, from 132.249.238.135. Once we test on all browsers, let's redirect from besuave

**Comment by izaslavsky** [comment]
Shall we rename " Add a survey" to "My surveys"?

**Comment by liside** [comment]
I've changed default address to suave.sdsc.edu

**Comment by izaslavsky** [comment]
Is there an additional step in WP to make it show
http://suave.sdsc.edu/gallery instead of http://suave.sdsc.edu/?page_id=61

**Comment by liside** [comment]
Yes, wordpress has a permanent link option in "Settings", but it failed to do the job. It must be some linux configurations, so I'll figure it out later.

**Comment by liside** [comment]
Done.
