### ISSUE TITLE
Updating links in http://besuave.azurewebsites.net/news/ and the ubuntu version

### ISSUE THREAD

**Issue by izaslavsky** [liside/SuAVE#23]
Some links pointed to files on copy.com, which no longer work. Here are the changes (5 edits needed)

5.	January 23, 2015. Advisory committee meeting, timed with the the EarthCube Stakeholder Alignment project’s writing session in San Diego. We presented the newest version of SuAVE and showed the capabilities of the authoring system using data from Nick Berente. (Powerpoint presentation)

Let’s remove the link, I can’t find it

7.	April 2015. Presentation at UCSD Design Rendezvous, at CalIT2 Design Lab, 4/14/2015 (Powerpoint)

New link: https://www.dropbox.com/s/g4r3k1gm5o4kkav/SUAVE_design_April14.pptx?dl=0

31. January 2016. SuAVE is presented at NSF, January 11th (PPT) 

New link: https://www.dropbox.com/s/ozjnelufrz2msiw/SUAVE_NSF_Jan%202016.pptx?dl=0

34. February 2016. Presentation at the AABSS conference (PPT) 

New Link: https://www.dropbox.com/s/uwgisd2z3i48tjq/Zaslavsky_AABSS.pptx?dl=0

36. February 2016. SuAVE poster is presented at NSF SI2 PI Workshop (PDF)

New Link: https://www.dropbox.com/s/n5ycnj43mgzv4k7/SUAVE_poster_2016_21x16.pdf?dl=0

**Comment by liside** [comment]
Done
