### ISSUE TITLE
Additions to authoring

### ISSUE THREAD

**Issue by izaslavsky** [liside/SuAVE#26]
Need to define #iname (currently undefined), and also ask for explanatory text (to appear under "About Survey. 
Perhaps an additional question about whether they want to further customize the survey - then please contact us.

Eventually, we'd need to allow people to adjust qualifiers (eg #date, #long, #number, #ordinal, #hidden) - for now we'll just expect that in the uploaded csv
Also, we may want to make smaller the icons and colors that appear in the color and icon assignment menu (under Edit)

**Comment by liside** [comment]
What's "#iname"? Is it the name of survey? Icons have been made smaller.

**Comment by izaslavsky** [comment]
Thinking about better ways to organize the authoring interface (under Edit):

1) Have two DIVs which you can expand or collapse. One can be called "1. Select a variable to visualize using colors", and the other "2. Select a variable to visualize using shapes". Alternatively, these could be radio buttons for each question, ie to "Select a variable to visualize using colors", or "don't associate any variable with colors". Selecting the first would expand the dialog.

2) When expanded, this will open the assignment dialog (perhaps emphasize that this is an expanded piece by putting it against gray background or something like that)

3) Pre-assign colors and shapes, and suggest that users click on the color/shape to re-assign.

**Comment by izaslavsky** [comment]
When the #name is added, I think I will have enough to generate a demo for NSF taking a spreadsheet from fastlane and adding it to Suave. Let me know; we might try to walk through it together.

**Comment by izaslavsky** [comment]
It should be possible to also also specify Bing maps or OpenStreetMap instead of Google map

**Comment by liside** [comment]
“#name" added

**Comment by liside** [comment]
"#date, #long, #number, #ordinal, #hidden" highlighted

**Comment by liside** [comment]
other tags added
